export const ACTION_TYPES = {
  TOGGLE_LOGIN_STATE: 'TOGGLE_LOGIN_STATE',
  TOGGLE_SNACK_STATE: 'TOGGLE_SNACK_STATE',
  NEW_MESSAGE: 'NEW_MESSAGE',
  UPDATE_USER: 'UPDATE_USER',
  REFETCH_AVATAR: 'REFETCH_AVATAR'
}